general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

background {
    monitor =
    path = /home/haluk/repos/.dotfiles/wallpapers/lain2.jpeg
    color = rgb(25, 23, 36) # Rosé Pine Base
    blur_passes = 2 
    blur_size = 7
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    
    # Rosé Pine Renkleri
    outer_color = rgb(49, 116, 143) # Pine (Dış Çerçeve)
    inner_color = rgba(31, 29, 46, 0.8) # Surface (İç Arkaplan)
    font_color = rgb(224, 222, 244) # Text (Yazı Rengi)
    check_color = rgb(246, 193, 119) # Gold (Doğrulanırken)
    fail_color = rgb(235, 111, 146) # Love (Yanlış Şifre)
    
    fade_on_empty = false
    placeholder_text = <i><span foreground="##908caa">Password...</span></i>
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    hide_input = false
    position = 0, -120
    halign = center
    valign = center
}

# Saat
label {
    monitor =
    text = $TIME
    color = rgb(224, 222, 244) # Text
    font_size = 90
    font_family = JetBrains Mono Nerd Font ExtraBold
    position = 0, 100
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 3
}

# Tarih
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%d %B %A")"
    color = rgb(156, 207, 216) # Foam
    font_size = 22
    font_family = JetBrains Mono Nerd Font
    position = 0, 10
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 2
}

# Karşılama
label {
    monitor =
    text = Welcome, Haluk
    color = rgb(235, 188, 186) # Rose
    font_size = 18
    font_family = JetBrains Mono Nerd Font
    position = 0, -50
    halign = center
    valign = center
}
