[main]
gtk-theme=Adwaita-dark
style=/home/haluk/.config/gtklock/style.css
# Duvar kağıdını kilit ekranına oturtur
modules=

[header]
# Saat ve Tarih formatı (GNOME tarzı)
time-format=%H:%M
date-format=%A, %d %B
